version: "3.8"
services:

  api:
      build: 
        context: ./
        dockerfile: Dockerfile
      container_name: api
      mem_limit: 512m
      networks:
        - madrobot
      ports:
        - "8080:80"
      restart: always

  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      mem_limit: 128m
      networks:
        - madrobot
      restart: always

networks:
  madrobot:
    driver: bridge
    name: madrobot